### ISSUE TITLE
postgress-init.py fault

### ISSUE THREAD

**Issue by mupsje** [No767/Kumiko#144]
hi, I created a postgress server on proxmox with all needed in .env
when I start command from /scripts 
python postgres-init.py

I get fault.
```
root@ubuntu:~/Kumiko/Bot# cd ..
root@ubuntu:~/Kumiko# cd scripts/
root@ubuntu:~/Kumiko/scripts# python postgres-init.py 
Traceback (most recent call last):
  File "/root/Kumiko/scripts/postgres-init.py", line 42, in <module>
    asyncio.run(main())
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/Kumiko/scripts/postgres-init.py", line 34, in main
    await utils.initUserTables(uri=CONNECTION_URI)
  File "/root/Kumiko/Bot/economy_utils/eco_user.py", line 49, in initUserTables
    engine = create_async_engine(
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 43, in create_async_engine
    sync_engine = _create_engine(*arg, **kw)
  File "<string>", line 2, in create_engine
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 725, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 781, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
root@ubuntu:~/Kumiko/scripts# 
```
inside .env in /Bot directory

```
POSTGRES_PASSWORD = "password"
Postgres_IP = 192.168.87.5 
POSTGRES_USER = "kumiko"
Postgres_Database = "kumiko_eco_users"
```
When I go to the Database ip, I can login.

regards Remco

**Comment by No767** [comment]
oh try moving the postgres-init.py script into the bot directory. that should solve it

**Comment by No767** [comment]
should have fixed it. Pull the latest changes, and move the postgres-init.py script back into the scripts folder. Hopefully should work now

**Comment by mupsje** [comment]
ty, for the update.
let you know when it is fixed

**Comment by No767** [comment]
np
